# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["github.com/ipfs/go-ipfs/repo/config", "github.com/karalabe/hid", "github.com/satori/go.uuid", "github.com/ipsn/go-ipfs*"]


# IPFS

[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  branch = "master"

[[constraint]]
  name = "github.com/RTradeLtd/go-ipfs-api"
  branch = "master-rtrade"
  
[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.7.21"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-dnslink"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-api"
  version = "1.2.7"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-ipfs-keystore"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-ipns"

[[constraint]]
  name = "github.com/ipfs/ipfs-cluster"
  version = "0.5.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "1.6.2"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  branch = "master"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.5"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-cmdkit"
  branch = "master"
  
# MISC

[[constraint]]
  name = "github.com/appleboy/gin-jwt"
  version = "2.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/aviddiviner/gin-limit"

[[constraint]]
  branch = "master"
  name = "github.com/c2h5oh/datasize"

[[constraint]]
  branch = "master"
  name = "github.com/danielkov/gin-helmet"

[[constraint]]
  name = "github.com/dvwright/xss-mw"
  version = "1.0.0-Beta"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.11"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/rollbar"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"



[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/goamz"

[[constraint]]
  branch = "master"
  name = "github.com/onrik/ethrpc"

[[constraint]]
  branch = "master"
  name = "github.com/rivo/tview"

[[constraint]]
  name = "github.com/segmentio/go-route53"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/semihalev/gin-stats"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/stvp/roll"

[[constraint]]
  name = "github.com/tus/tusd"
  version = "0.10.0"

[[constraint]]
  branch = "master"
  name = "github.com/zsais/go-gin-prometheus"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/sessions"
