ignored = ["github.com/karalabe/hid", "github.com/satori/go.uuid", "github.com/ipfs/go-ipfs", "github.com/RTradeLtd/Temporal_Payment-ETH"]

[prune]
  go-tests = true
  unused-packages = true

###############
#   RTRADE    #
###############


[[constraint]]
  name = "github.com/RTradeLtd/ChainRider-Go"
  version = "v1.0.7"

[[override]]
  name = "github.com/RTradeLtd/grpc"
  branch = "master"

[[override]]
  name = "github.com/RTradeLtd/database"
  branch = "gorm"

[[override]]
  name = "github.com/RTradeLtd/rtfs"
  branch = "master"
  
[[constraint]]
  name = "github.com/RTradeLtd/config"
  branch = "master"

[[constraint]]
  name = "github.com/RTradeLtd/cmd"
  version = "v1.0.4"

[[constraint]]
  name = "github.com/RTradeLtd/crypto"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/RTradeLtd/go-ipfs-api"
  version = "v2.0.4"

[[constraint]]
  name = "github.com/RTradeLtd/kaas"
  version = "v1.0.2"

###############
#    IPFS     #
###############


[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  branch = "master"
  
[[override]]
  name = "github.com/multiformats/go-multibase"
  version = "0.3.0"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-dnslink"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-ipfs-keystore"

[[constraint]]
  name = "github.com/ipfs/ipfs-cluster"
  branch = "master"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "2.0.1"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  branch = "master"


[[constraint]]
  name = "github.com/ipfs/go-ipfs-config"
  version = "0.2.4"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  branch = "master"

[[override]]
  name = "github.com/ipfs/go-ipfs-cmdkit"
  branch = "master"

###############
# THIRD PARTY #
###############


[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/aviddiviner/gin-limit"

[[constraint]]
  branch = "master"
  name = "github.com/c2h5oh/datasize"

[[constraint]]
  branch = "master"
  name = "github.com/danielkov/gin-helmet"

[[constraint]]
  name = "github.com/dvwright/xss-mw"
  version = "1.0.0-Beta"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/semihalev/gin-stats"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/zsais/go-gin-prometheus"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[override]]
  name = "github.com/rjeczalik/notify"
  branch = "master"

[[constraint]]
  name = "github.com/NebulousLabs/entropy-mnemonics"
  branch = "master"
  
[[constraint]]
  name = "github.com/appleboy/gin-jwt"
  revision = "f7347d7c16fc8297bf5b7215b9e4847a5ca05d90"
