ignored = ["github.com/karalabe/hid", "github.com/satori/go.uuid", "github.com/ipfs/go-ipfs", "github.com/RTradeLtd/Temporal_Payment-ETH"]

[prune]
  go-tests = true
  unused-packages = true

# RTrade

[[constraint]]
  name = "github.com/RTradeLtd/grpc"
  version = "v1.0.3"
  
[[constraint]]
  name = "github.com/RTradeLtd/config"
  version = "v1.0.5"

[[constraint]]
  name = "github.com/RTradeLtd/cmd"
  version = "v1.0.1-rc1"

[[constraint]]
  name = "github.com/RTradeLtd/crypto"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/RTradeLtd/go-ipfs-api"
  version = "v2.0.0"

# IPFS

[[override]]
  name = "github.com/multiformats/go-multiaddr-dns"
  branch = "master"
  
[[constraint]]
  name = "github.com/ipfs/go-cid"
  version = "0.7.21"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-dnslink"

[[constraint]]
  branch = "master"
  name = "github.com/ipfs/go-ipfs-keystore"

[[constraint]]
  name = "github.com/ipfs/ipfs-cluster"
  version = "0.5.0"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-crypto"
  version = "1.6.2"

[[constraint]]
  name = "github.com/multiformats/go-multiaddr"
  branch = "master"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.5"

# MISC

[[constraint]]
  branch = "master"
  name = "github.com/aviddiviner/gin-limit"

[[constraint]]
  branch = "master"
  name = "github.com/c2h5oh/datasize"

[[constraint]]
  branch = "master"
  name = "github.com/danielkov/gin-helmet"

[[constraint]]
  name = "github.com/dvwright/xss-mw"
  version = "1.0.0-Beta"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  branch = "master"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/goamz"

[[constraint]]
  name = "github.com/segmentio/go-route53"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/semihalev/gin-stats"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "github.com/zsais/go-gin-prometheus"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  name = "github.com/ipfs/go-ipfs-config"
  version = "0.2.4"

[[override]]
  name = "github.com/rjeczalik/notify"
  branch = "master"

[[constraint]]
  name = "github.com/libp2p/go-libp2p-peer"
  branch = "master"

[[override]]
  name = "github.com/ipfs/go-ipfs-cmdkit"
  branch = "master"

[[constraint]]
  name = "github.com/appleboy/gin-jwt"
  revision = "f7347d7c16fc8297bf5b7215b9e4847a5ca05d90"
